version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db_2  # Setting container name to mysql_db_2
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_2
    environment:
      PMA_HOST: mysql_db_2  # Updated to use mysql_db_2 as the host
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      - mysql

  website:
    build:
      context: .
      dockerfile: docker-apache-php
    container_name: website_2
    volumes:
      - ./site:/var/www/html
    depends_on:
      - mysql
    ports:
      - "8081:80"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy_2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - website
      - phpmyadmin

